# Generated by Django 4.2.26 on 2026-08-23 10:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hat',
            name='discount',
            field=models.PositiveIntegerField(default=0, help_text='Discount percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('hat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.hat')),
            ],
        ),
    ]
